### ISSUE TITLE
Osm PokeAssistant

### ISSUE THREAD

**Issue by HOPE-NEXUS** [TrashUwU/PokeAssistant#11]
👏 Let's clap for the Developers of PokeAssistant who brought out.

I have seen it has achieved Better Accuracy and is being Updated Frequently!
It even got Commands to help you out like `Shiny hunt pings` and Few others 😄 

Must give it a try Friends.

Only 1 issue i have seen in the bot is :- 
- It keeps typing... but doesn't reply the pokemon name(sometimes).

That's it, pretty forward and Best of Luck (devs and Users)

**Comment by TrashUwU** [comment]
Thanks for your lovely comment ♥! Just moved to api, it's getting slow and unresponsive. Will buy a better infrastructure for hosting API soon.

Note: Your AI is awesome ;)

**Comment by HOPE-NEXUS** [comment]
> 
> 
> Thanks for your lovely comment ♥! Just moved to api, it's getting slow and unresponsive. Will buy a better infrastructure for hosting API soon.
> 
> Note: Your AI is awesome ;)

You can use Our AI API , it got modes and works for poketwo with 99.98% accuracy.
We are soon globalizing our APIs for Public usage.

Ah,Thanks you liked the comment!
