### ISSUE TITLE
Can't repel

### ISSUE THREAD

**Issue by dipin746130k** [TrashUwU/PokeAssistant#13]
I can't repel it shows waking the repel for long time and doesn't repel also

**Comment by TrashUwU** [comment]
What?

**Comment by TrashUwU** [comment]
Visit https://github.com/TrashUwU/PokeAssistant/raw/main/src/package.json and copy the code. Paste it in the package.json of your bot cod/repl.

**Comment by OwnGooal** [comment]
What is Repel?
