### ISSUE TITLE
Hi i have one problem 

### ISSUE THREAD

**Issue by loco15720** [TrashUwU/PokeAssistant#2]
I don't know why I do everything as it says on the vidio and when I try to press the button and turn on the bot I get this attached photo
![Screenshot_2021-04-21-12-48-00-301_com android chrome](https://user-images.githubusercontent.com/82939993/115546157-fa250b00-a2a4-11eb-8030-8cc246bfc8ad.jpg)

**Comment by TrashUwU** [comment]
Make sure you have created a secret called **CHANNEL**. Here is an updated tutorial https://drive.google.com/file/d/1-dtNyLJxo73Ls9nArb20AESOLx3yuCXv/view?usp=drivesdk

**Comment by TrashUwU** [comment]
Read the guide, and don't skip anything. And it will work like a charm.
