### ISSUE TITLE
My bot doesnt ping for shiny hunts 

### ISSUE THREAD

**Issue by Destiny404** [TrashUwU/PokeAssistant#20]
![Screenshot_2021_0731_183758](https://user-images.githubusercontent.com/87466810/127740907-78d6fcd6-3dea-4da7-8c21-10f270bb8161.jpg)
Doesnt ping for some hunts

**Comment by TrashUwU** [comment]
Is [this](https://github.com/TrashUwU/PokeAssistant/blob/main/src/TROUBLESHOOT.md#6-error-of-sh-ping-none-or-quest-ping-none-everytime) the issue?
