### ISSUE TITLE
error finding pokemon/wrong name

### ISSUE THREAD

**Issue by giffy0987** [TrashUwU/PokeAssistant#22]
**Describe the bug**
1. Every couple of Pokemon the bot cant seem to give the name anymore. I will need to restart the complete bot cause Rebooting isnt enough. 
2. The pokemon gives the wrong name for pokemons even easy ones. 

**Expected behavior**
1. I expect a way I can solve this by just a button or a Command for the bot. su!reboot does not work. 
2. I Dont expect the bot to get everything right, but last time he said Pidove looked like Squirtle.. 

**Screenshots**
1.  ![image](https://user-images.githubusercontent.com/90920799/134163072-c72688d7-bcec-463f-9506-dd820e537137.png)
2. 
![image](https://user-images.githubusercontent.com/90920799/134163562-1e0c663c-adcf-429e-94a9-fe8de18b8cea.png)

**Additional context**
1. It tries it a couple of times, then it gives a message to reboot but after reboot it will still not work. I need to go into Replit to pull the bot offline and back online again. 
2. I know Gen 8 isnt completly working yet, but the other gens have also errors in it. As seen in the picture the bot thought Pidove was squirtle. Again I dont expect the bot to be 100% right all the time just reporting it cause I noticed it :)

**Comment by TrashUwU** [comment]
I don't know what's causing the error.

**Comment by giffy0987** [comment]
neither do I, I followed all the steps but it keeps crashing it will just say its typing constantly.

![image](https://user-images.githubusercontent.com/90920799/134230364-77a5325e-36c7-41e9-9192-69a29e54902b.png)

**Comment by TrashUwU** [comment]
> neither do I, I followed all the steps but it keeps crashing it will just say its typing constantly.
> 
> ![image](https://user-images.githubusercontent.com/90920799/134230364-77a5325e-36c7-41e9-9192-69a29e54902b.png)

It's happening with your bot only!

**Comment by TrashUwU** [comment]
You can try running the bot on a new repl.
