### ISSUE TITLE
I set my ID as owner but I can't run Owner only commands

### ISSUE THREAD

**Issue by RehanPlayz** [TrashUwU/PokeAssistant#24]
**Is your feature request related to a problem? Please describe.**
I set my ID as owner but I can't run Owner only commands [The Bot Owner in discord dev portal is my alt and my alt can run commands to fine] (Eg: tb!reboot)

**Comment by RehanPlayz** [comment]
Also Prefix isn't working I set the prefix to "po" but it doesn't work

**Comment by TrashUwU** [comment]
> Also Prefix isn't working I set the prefix to "po" but it doesn't work

It works.

**Comment by TrashUwU** [comment]
The owner of the bot will be considered "OWNER".
