### ISSUE TITLE
Disable Auto Identify

### ISSUE THREAD

**Issue by Pandafuchs** [TrashUwU/PokeAssistant#29]
I know that the bot is currently deprecated because of replit issues. Can you please add a flag to disable the auto detection that fails all the time? I would like to only use the p!hint method which works perfectly imho.

So in conclusion maybe add an Env. Variable to enable Hint-Mode Only.

**Comment by Xurxese** [comment]
How can I do that? I would love to get it to stop that myself.

**Comment by TrashUwU** [comment]
Remove the `CHANNEL` secret and it'll work.
