### ISSUE TITLE
Mention for Shiny Hunt

### ISSUE THREAD

**Issue by HaxorusPro** [TrashUwU/PokeAssistant#3]
Not an issue. Just a feature request. I want set a pokemon like `Skrelp`. Whenever a skrelp spawn in a server and I am also in the server the bot ping me

**Comment by TrashUwU** [comment]
Coming soon!

**Comment by TrashUwU** [comment]
Yeah here it is!
https://github.com/TrashUwU/PokeAssistant/releases/tag/v2.1.0
