### ISSUE TITLE
failed to predict spawm

### ISSUE THREAD

**Issue by akashkroos970** [TrashUwU/PokeAssistant#30]
**Describe the bug**
the bot is unable to predict spawns its shows failed to predict and tells to reboot I did reboot still same problem 

**Expected behavior**
I expected the bot to work after reboot but I dint pls help

**Screenshots**

**Additional context**
I have opened a ticket in support server if possible contact me there too channel id is 928538174437883955
![image_2022-01-06_123427](https://user-images.githubusercontent.com/80937245/148342655-ca5e455c-98d6-48b4-bd65-e6be7d2f49a9.png)

**Comment by thorvak** [comment]
Same everytime I got fail

**Comment by Xurxese** [comment]
That's just the way it is, it needs re-coded. That may take some time and that's saying trash even wants to...I'm sure it's a pain keeping up with all of that code that was originally outdated and abandoned when trash tried to resurrect/save it.

**Comment by TrashUwU** [comment]
Check Readme
