### ISSUE TITLE
Bot goes offline often

### ISSUE THREAD

**Issue by lastedito** [TrashUwU/PokeAssistant#32]
**Describe the bug**
The bot goes offline time to time and I have to restart it on replit (uptimerobot is setup) (about every 1-2h i'd say)

**Expected behavior**
Having a bot that stays on 12h at least if not 24/7

**Screenshots**

**Additional context**
I have no idea if its supposed to be like this or not ^^
Please help! 
Thanks

**Comment by ObliviousDonkey** [comment]
I had same issue, but figured out it's due to incorrect setup of Uptimerobot. What repl link did you put in uptimerobot?

**Comment by TrashUwU** [comment]
You didn't put correct link uptimerobot.

**Comment by lastedito** [comment]
Hello, I've put this (ty for answering) : https://PokeAssistant.lastedito.repl.co   
from here :
![image](https://user-images.githubusercontent.com/11960432/163073856-84bcd9de-1dc8-4cbe-ab32-e046bb1cf831.png)

here is what uptimerobot looks like :
![image](https://user-images.githubusercontent.com/11960432/163074263-9cd55d6e-8454-4d65-abd9-bbf0168db2c5.png)

**Comment by TrashUwU** [comment]
Can you type `kill 1` in shell and press enter?

**Comment by lastedito** [comment]
few days ago it was showing im alive (and still stopped time to time tho)

**Comment by Xurxese** [comment]
This has been an ongoing occurrence for quite some time now I believe it’s not going to be fixed.

**Comment by TrashUwU** [comment]
Fork it and run on a different REPL. The bot is working fine for me. Your repl is not showing `I'm alive`, that could be the bug.

**Comment by MrTac0** [comment]
i have this issue too. After like 1 day the bot will go offline, but on uptimerobot is shows 100% up. For make him go online again i need to go on replit and click start  again
