### ISSUE TITLE
BOT does NOT come online

### ISSUE THREAD

**Issue by asianalexa** [TrashUwU/PokeAssistant#35]
I follow each step very carefully and do everything the same and when running the code thing the code doesnt come online, all of my bot tokens and everything is ok it just wont come online, the only thing i am unsure about is getting my bot token, whenever i reset my bots token it says "Your bot will stop working until you update the token in your bot's code." maybe that is the issue but even if it is i dont know how to resolve it.

**Comment by TrashUwU** [comment]
Please, read troubleshooting page.
