### ISSUE TITLE
the bot is offine and isnt starting up

### ISSUE THREAD

**Issue by ashgreninja736** [TrashUwU/PokeAssistant#36]
i put in the ids and stuff but it wont turn on

i thought it turn on but wont

**Screenshots**
![image](https://user-images.githubusercontent.com/112594960/187813939-e03f321f-bec6-4369-939f-f3341bd61b47.png)
i would show the bot not working but i cant because idk how

can u at least make it show the pc version of the video

**Comment by TrashUwU** [comment]
Read troubleshooting.md
