### ISSUE TITLE
bot not coming online

### ISSUE THREAD

**Issue by angeliclambie** [TrashUwU/PokeAssistant#38]
I watched the video and followed every step as shown, but the bot won't come online no matter what I do. I clicked run, it said running, but when I check my server the bot is offline. The uptime site to keep it up is working fine, too. Not sure what else to do ):
![unknown](https://user-images.githubusercontent.com/116236704/196841241-f04c6c9e-9439-4dcf-84b2-59d85887efe7.png)

**Comment by Sias27** [comment]
I am running into the same issue

**Comment by Somnath6817** [comment]
Same issue

**Comment by TrashUwU** [comment]
It'll work now.
