### ISSUE TITLE
Poketwo bot offline issue 

### ISSUE THREAD

**Issue by Somnath6817** [TrashUwU/PokeAssistant#43]
![Screenshot_2022_1204_191143](https://user-images.githubusercontent.com/119339938/205493967-9a1d51d9-5a1c-4d61-886c-f59da1ae3538.jpg)
**Describe the bug**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Somnath6817** [comment]
Please

**Comment by TrashUwU** [comment]
🥴
